apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitops-demo-app.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "gitops-demo-app.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      nodePort: {{ .Values.service.nodePort }}
